server:
  port: 8080

spring:
  datasource:
    username: root
    password: your-password
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  ai:
    openai:
      api-key: your-api-key
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat

#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: entity
#  configuration:
#    cache-enabled: true  # 开启二级缓存

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.example.demo.entity

logging:
  level:
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG
    com.example.demo: DEBUG